version: '3.5'

services:
    postgres:
        container_name: test_user_postgres
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
    postgres:
